garagesale/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path, include
from . import views

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('marketplace/', views.marketplace, name='marketplace'),
    path('inventory/', views.inventory, name='inventory'),
    path('inventory/create/', views.ProductCreate.as_view(), name='product_create'),
    path('inventory/<int:pk>/update/', views.ProductUpdate.as_view(), name='products_update'),
    path('inventory/<int:pk>/buy/', views.ProductBuy.as_view(), name='products_buy'),
    path('profile/', views.profile, name="profile"),
    path('profile/create/', views.ProfileCreate.as_view(), name='profile_create'),
    path('profile/<int:pk>/update/', views.ProfileUpdate.as_view(), name="profile_update"),
    path('inventory/<int:product_id>', views.products_detail, name='detail'),
    path('inventory/<int:pk>/delete', views.ProductDelete.as_view(), name='product_delete'),
    # path('inventory/<int:product_id>/deletephoto/', views.PhotoDelete, name='photo_delete'),

    path('inventory/<int:product_id>/photo_products', views.photo_products, name='photo_products'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)    
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.IntegerField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'product_id': self.id})

class ProductPhoto(models.Model):
  url = models.CharField(max_length=200)
  product = models.ForeignKey(Product, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for product_id: {self.product_id} @{self.url}"

class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    favorite_color = models.CharField(max_length=50, blank=True, default="blue")
    
    ## balance 

    def __str__(self):
        return str(self.user)
    
    def get_absolute_url(self):
        return reverse('profile')

main_app/forms.py
from django.views.generic import CreateView
from .models import Product
from django.forms import ModelForm

class ProductForm(ModelForm):
  class Meta:
    model = Product
    fields = ['title', 'description', 'price', 'quantity', 'for_sale']

  def form_valid(self, form):
    form.instance.user = self.request.user  # form.instance is the cat
    return super().form_valid(form)

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
import boto3
from django.contrib.auth.forms import UserCreationForm

from .models import Product, Profile, ProductPhoto
from django.views.generic.edit import CreateView, UpdateView, DeleteView

S3_BASE_URL = 'https://s3.ca-central-1.amazonaws.com/'
BUCKET = 'garagesaled'

def home(request):
  return render(request, 'home.html')

def marketplace(request):
  products = Product.objects.all()
  return render(request, 'products/marketplace.html', { 'products': products})

@login_required
def inventory(request):
  products = Product.objects.filter(user=request.user)
  return render(request, 'products/inventory.html', { 'products': products})

@login_required
def products_detail(request, product_id):
  product = Product.objects.get(id=product_id)

  return render(request, 'products/detail.html', { 
    'product': product,
  })

class ProductCreate(CreateView, LoginRequiredMixin):
  model = Product
  fields = ['title', 'description', 'price', 'quantity', 'user']

  def form_valid(self, form):
      form.instance.user = self.request.user 
      return super().form_valid(form)

  success_url = '/inventory/'

class ProductUpdate(UpdateView, LoginRequiredMixin):
  model = Product
  fields = ['description', 'price', 'quantity']

class ProductBuy(UpdateView):
  model = Product
  fields = ['description', 'price', 'quantity']
  success_url = '/marketplace/'

class ProductDelete(DeleteView, LoginRequiredMixin):
  model = Product
  success_url = '/inventory/'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('inventory')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

@login_required
def profile(request):
  print(request.user.id)
  p = Profile.objects.filter(user_id=request.user.id)
  if len(p) > 0:
    print("USER PROFILE FOUND")
    return render(request, 'users/index.html')
  else:
    print("USER PROFILE NOT FOUND")
    return render(request, 'users/add_profile.html')


class ProfileCreate(CreateView, LoginRequiredMixin):
    model = Profile
    fields = ['bio', 'favorite_color']

    def form_valid(self, form):
        form.instance.user = self.request.user 
        return super().form_valid(form)

    success_url = '/profile/'

class ProfileUpdate(UpdateView, LoginRequiredMixin):
  model = Profile
  fields = ['bio', 'favorite_color']

@login_required
def photo_products(request, product_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      s3.upload_fileobj(photo_file, BUCKET, key)
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      photo = ProductPhoto(url=url, product_id=product_id)
      photo.save()
    except:
      print('An error occurred uploading file to S3')
  return redirect('detail', product_id=product_id)

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Digital Garage Sale</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper {{user.profile.favorite_color}} lighten-3">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Digital Garage Sale</a></li>
        </ul>
        <ul class="right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'marketplace' %}">Marketplace</a></li>
            <li><a href="{% url 'inventory' %}">View My Inventory</a></li>
            <li><a href="{% url 'profile' %}">Profile</a></li>
            <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'marketplace' %}">Marketplace</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer {{user.profile.favorite_color}} lighten-3">
    <div class="right black-text">All Rights Reserved, &copy; 2021 Digital Garage Sale &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

{% if user.is_authenticated %}
    <div class="center">
        <h1>Hello {{ user.username }}</h1>
        <h3>Newest Products</h3>
    </div>
{% else %}
    <div class="center">
        <h1>Hello Guest</h1>
        <h3>Newest Products</h3>
    </div>
{% endif %}

{% endblock %}

main_app/templates/main_app/photo_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Photo</h1>

  <h4>Are you sure you want to delete this photo?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn {{user.profile.favorite_color}} lighten-3">
    <a href="{% url 'detail' product.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/product_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Product</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' product.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/product_form.html
</style>
{% extends 'base.html' %}
{% block content %}

{% if user != product.user and product %}
  <div id="buy-product">

    <h1>{{ product.title }}</h1>

    <div class="card">
          <div class="card-content">
              <h1>Confirm Purchase</h1>
              <span class="card-title">{{ product.title }}</span>
              <p>Description: {{ product.description }}</p>
              <p>Price: ${{ product.price }}</p>
              <p>Please read our <a target="_blank" href="https://ottawa.ctvnews.ca/garage-sales-allowed-to-open-in-ottawa-as-covid-restrictions-ease-1.5475943">Terms and Conditions</a></p>
          </div>
    </div>

  </div>
{% endif %}


<form action="" method="post" id="product-form">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" class="btn {{user.profile.favorite_color}} lighten-3">
</form>


{% if user != product.user and product %}

<script>
  console.log("This is working. ")

  const elems = {
    buyButton: document.querySelector('.btn'),
    quantityInput: document.getElementById('id_quantity'),
    descInput: document.getElementById('id_description'),
    priceInput: document.getElementById('id_price'),
    descLabel: document.querySelector('[for="id_description"]'),
    priceLabel: document.querySelector('[for="id_price"]'),
    quantityLabel: document.querySelector('[for="id_quantity"]'),
    buyInfo: document.getElementById('buy-product')
  }

  elems.buyButton.value = 'Buy';
  elems.quantityInput.value = elems.quantityInput.value - 1;

  elems.quantityInput.hidden = true;
  elems.descInput.hidden = true;
  elems. priceInput.hidden = true;
  elems.descLabel.hidden = true;
  elems.priceLabel.hidden = true;
  elems.quantityLabel.hidden = true;
</script>


{% endif %}

{% endblock %}

main_app/templates/main_app/profile_form.html
{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
<style>
  .color-choice {
    width: 50px;
    height: 50px;
    border: 1px solid black;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  .color-container {
    display: flex;
    justify-content: start;
    padding: 10px 0px;
  }
  .input-field {
    background-color: aliceblue;
  }
  .purple {background-color: blueviolet;}
  .red {background-color: red;}
  .blue {background-color: blue;}
  .green {background-color: green;}
  .pink {background-color: pink;}
  .yellow {background-color: yellow;}

  a {
    text-decoration: none;
    color: black;
  }
</style>



<h1>Profile Create Page</h1>

{{ user.username }}
<form action="" method="post" id="profile-form">
  {% csrf_token %}
  {{ form.as_p }}
  <div class="color-container">
    <div class="red color-choice "><a onclick="M.toast({html: 'Red'})">Red</a></div>
    <div class="blue color-choice"><a onclick="M.toast({html: 'Blue'})">Blue</a></div>
    <div class="green color-choice"><a onclick="M.toast({html: 'Green'})">Green</a></div>
    <div class="yellow color-choice"><a onclick="M.toast({html: 'Yellow'})">Yellow</a></div>
    <div class="pink color-choice"><a onclick="M.toast({html: 'Pink'})">Pink</a></div>
    <div class="purple color-choice">  <a onclick="M.toast({html: 'Purple'})">Purple</a></div>
  </div>

  <input type="submit" value="Submit" class="btn {{user.profile.favorite_color}} lighten-3">
</form>

<script defer>
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.carousel');
    var instances = M.Carousel.init(elems, options);
  });

  const formElems = {
    form: document.getElementById('profile-form'),
    bio: document.getElementById('id_bio'),
    favorite_color: document.getElementById('id_favorite_color'),
    color_choices: document.querySelectorAll('.color-choice')
  }

  console.log(formElems.color_choices)
  for (color of formElems.color_choices) {
    color.addEventListener('click', (e) => {
      console.log(e.target.innerText)
      formElems.favorite_color.value = e.target.innerText.toLowerCase()
      console.log(formElems.favorite_color.value)
    })
  }

  console.log(formElems.favorite_color.value)
  formElems.favorite_color.readOnly = true;
  formElems.favorite_color.classList.add('input-field');

  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.tooltipped');
    var instances = M.Tooltip.init(elems, options);
  });

</script>

{% endblock %}

main_app/templates/products/detail.html
{% extends 'base.html' %}
{% block content %}

<h1 class='center'>{{ product.title }}</h1>

  <div class="card" style="height: 300px">
        <div class="card-content" style="height: 245px">
            {% for photo in product.productphoto_set.all %}
              <img class="right responsive-img {{user.profile.favorite_color}}-text lighten-3" style="width: auto; height: 175px;" src="{{photo.url}}">
            {% empty %}
              <div class="right center-align {{user.profile.favorite_color}}-text lighten-3">
                No Photos Uploaded
              </div>
              <form action="{% url 'photo_products' product.id %}" enctype="multipart/form-data" method="POST" class="right">
                {% csrf_token %}
                <input type="file" name="photo-file">
                <br><br>
                <input type="submit" class="btn {{user.profile.favorite_color}} lighten-3" value="Upload Photo">
              </form>
            {% endfor %}
            <p>Description: {{ product.description }}</p>
            <p>Price: ${{ product.price }}</p>
            <p>Quantity: {{ product.quantity }}</p>
        </div>
        <div class="card-action" style="height: auto">
            <a class="{{user.profile.favorite_color}}-text lighten-3" href="{% url 'products_update' product.id %}">Edit</a>
            <a class= "{{user.profile.favorite_color}}-text lighten-3" href="{% url 'product_delete' product.id %}">Delete</a>
        </div>
        
  </div>

{% endblock %}

main_app/templates/products/inventory.html
{% extends 'base.html' %}
{% block content %}

<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


<h1>{{ user.username }}'s Inventory</h1>

{% if products %}


  {% for product in products %}
    <div class="card">
      <a href="{% url 'detail' product.id %}">
          <div class="card-content">
              <span class="card-title">{{ product.title }}</span>
              <p>Description: {{ product.description }}</p>
              <p>Price: ${{ product.price }}</p>
              <p>Quantity: {{ product.quantity }}</p>

          </div>
      </a>
    </div>
   {% endfor %}
   <a class="waves-effect waves-light btn {{user.profile.favorite_color}} lighten-3" href="{% url 'product_create' %}">Add a Product</a>
{% else %}

<div class="row">
  <div class="col s12 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Add your first product!</span>
        <p>You have not yet listed your first product yet, get started below! </p>
        <br>

      </div>
      <div class="card-action">
        <a href="{% url 'product_create' %}" class="black waves-effect waves-light btn-large"><i class="material-icons left">add_box</i>ADD YOUR FIRST PRODUCT</a>
      </div>
    </div>
  </div>
</div>
{% endif  %}

{% if user.profile %}

{% else %}

<div class="collection">
  <a href="{% url 'profile_create' %}" class="collection-item"><span class="badge"><strong>Listings with photos typically sell for 500% more!</strong></span>You have not created your profile.</a>
    
</div>


{% endif %}

<script>


</script>

{% endblock %}

main_app/templates/products/marketplace.html
{% extends 'base.html' %}
{% block content %}

<h1 class="center">Marketplace</h1>

{% for product in products %}

  <div class="card" style="height: 300px">
        <div class="card-content" style="height: 245px">
            <span class="card-title">{{ product.title }}</span>
            {% for photo in product.productphoto_set.all %}
                <img class="right responsive-img {{user.profile.favorite_color}}-text lighten-3" style="width: auto; height: 175px;" src="{{photo.url}}">
            {% empty %}
                <div class="right center-align {{user.profile.favorite_color}}-text lighten-3">No Photos Uploaded</div>
            {% endfor %}
            <p>Description: {{ product.description }}</p>
            <p>Price: ${{ product.price }}</p>
            <p>Quantity: {{ product.quantity }}</p>
            <p>User: {{ product.user }}</p>
        </div>
        <div class="card-action" style="height: auto">
            {% if user == product.user %}
                <sapn class="material-icons"></span>
            {% elif product.quantity > 0 %}
                <a class="{{user.profile.favorite_color}}-text lighten-3" href="{% url 'products_buy' product.id %}">Buy</a>
            {% else %}
                <span class="red-text darken-3">Sold Out</span>
            {% endif %}
        </div>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/test.html
<form method="post" action="test/">
  {% csrf_token %}

  {{product_form.as_p}}

  <input type="submit" class="btn" value="Add Product">

</form>

main_app/templates/users/add_profile.html
{% extends 'base.html' %}
{% block content %}
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<h1>Hi {{ user.username }},</h1>

<div class="row">
  <div class="col s12 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text"> 
        <span class="card-title">Create your Profile</span>
        <p>You have not yet created your profile, please click below to continue to setup.</p>
      </div>
      <div class="card-action">
        <a href="{% url 'profile_create' %}" class="black waves-effect waves-light btn-large"><i class="material-icons left">person_pin</i>Get Started Now</a>
      </div>
    </div>
  </div>
</div>



{% endblock %}

main_app/templates/users/index.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ user.username }}</h1>

  <div class="card" style="height: 300px">
        <div class="card-content" style="height: 245px">
            <h3>Bio: {{ user.profile.bio }}</h3>
            <h3>Favourite Colour: <span class="{{ user.profile.favorite_color }}-text lighten-3">{{ user.profile.favorite_color }}</span> </h3>
        </div>
        <div class="card-action" style="height: auto">
            <a class="{{user.profile.favorite_color}}-text lighten-3" href="{% url 'profile_update' user.profile.id %}">Update</a>
        </div>       
  </div>

{% endblock %}